---
- name: Update package cache
  become: yes
  apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Update package cache
  become: yes
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Set MOTD
  become: yes
  template:
    src: motd.j2
    dest: /etc/motd
