---
- name: Install enterprise service on Debian
  become: yes
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install enterprise service on CentOS
  become: yes
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable enterprise service
  become: yes
  service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: started
    enabled: true

